project:
  type: website
  output-dir: docs
  resources: 
    - "*.pdf"

website:
  title: "Augustas Macijauskas"
  favicon: assets/favicon.ico
  navbar:
    right:
      - about.qmd
      - text: "Notes"
        file: notes.qmd
      - icon: github
        href: https://github.com/augustasio/
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/augustas-macijauskas/
        target: _blank
      - icon: twitter-x
        href: https://twitter.com/augustasio
        target: _blank
  twitter-card:
    creator: "@augustasio"
  open-graph:
    site-name: "Augustas Macijauskas's blog"
    # image: augustas-macijauskas-square-profile.jpg
  google-analytics:
    tracking-id: "G-1M6C1LWNHY"
    storage: cookies
    anonymize-ip: true
  cookie-consent:
    type: implied
format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    code-line-numbers: true
    highlight-style: github

comments:
  hypothesis:
    theme: clean
